### PR TITLE
Hyperlink DOIs against preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates all DOI links.

Cheers!

### CODE REVIEW

**Comment by jhpoelen** [comment]
@katrinleinweber just wondering - I am sure that many (java) developers have a need for a DOI extractor / matcher. Are you aware of any, I'd very much like to re-use on rather than using some hand made one? If not, would you be open to collaborating to creating a simple java library that matches, parses, validates and creates resolvable urls for dois?

**Comment by katrinleinweber** [comment]
I don't have Java experience, sorry. Have looked around with the help of a Java friend and we found nothing usable on https://bintray.com/bintray/jcenter nor https://search.maven.org/.

Maybe @claussni has some advice, because of https://github.com/slub/urnlib.

**Comment by jhpoelen** [comment]
Thanks for looking! For now, I've implemented my own, but hoping to re-use another lib once it appears on the horizon.

**Comment by claussni** [comment]
Hi @jhpoelen , what are actually you trying to do when "matching and extracting DOIs"? 
DOIs and DOI-URLs are actually URIs, so you can parse them:
```
URI uri = new URI("http://resolv.org/10.1371/journal.pone.0137353");
```
So this simple call would give you the DOI, cutting away the resolve URL (which is a host):
```
System.out.println(uri.getPath());
```

**Comment by jhpoelen** [comment]
@claussni much agreed that going from doi url to doi is helped with the URI class. However, consider a example in https://www.doi.org/syntax.html -
```
Hex encoding consists of substituting for the given character its hex value preceded by percent. Thus, # becomes %23 and

http://dx.doi.org/10.1000/456#789

is encoded as

http://dx.doi.org/10.1000/456%23789
```
Here's it is temping for java developers to say ```URI.create("http://dx.doi.org/10.1000/456#789")``` which would actually create a path of ```10.1000/456``` with fragment ```789```. This will not result in the expected encoding of  ```http://dx.doi.org/10.1000/456%23789```. 

Curious to hear your thoughts on this, maybe I am missing something.

**Comment by claussni** [comment]
Well, one way to make sure developers don't mess up is to use the type system. Introducing a final type `DOI` that provides the necessary parsing and serialization functionality. Until you have such a type, unit testing those edge cases in you code is in order.

**Comment by jhpoelen** [comment]
Yep, a DOI type would definitely help. Do you think it would help to create a java utility library just for this purpose?

**Comment by jhpoelen** [comment]
DOI.fromUrl(...)
DOI.create(...)
DOI.toUrl(optional resolv url, default https://doi.org)

**Comment by claussni** [comment]
A DOI library would make sense. I started https://github.com/slub/urnlib for similar reasons. And as an exercise in good library design 😏

**Comment by jhpoelen** [comment]
@claussni  following your example/recommendation, I took a stab at creating doi4j  a java library at https://github.com/globalbioticinteractions/doi4j . Is this what you had in mind?

**Comment by jhpoelen** [comment]
In my search, I found various blog posts like https://www.crossref.org/blog/dois-and-matching-regular-expressions/ and a clojure utility method by crossref https://github.com/CrossRef/util/blob/master/src/crossref/util/doi.clj . Also, I briefly looked at hcj , the handle.net client download. This client seems more like a standalone application that does many things, not a simple library to parse doi. Also, the hcj code does not seem to be design to be used in the library java ecosystem (e.g., not published in a maven repository). My simplest explanation for all this is that doi handling is perceived to be too simple to write a library for. I'd prefer to re-use someone else's (more established) library, so please holler if you find one.

**Comment by katrinleinweber** [comment]
> [...] perceived to be too simple

Whereas one step before, [URL redirection](https://en.wikipedia.org/wiki/URL_redirection) is perceived as sooo difficult that it should really be solved by outsourcing it. Et voila: the DOI system ;->

**Comment by claussni** [comment]
Exactly, yes. I do have some issues with coding and testing style, though...

**Comment by jhpoelen** [comment]
@claussni am open to suggestions, if you care to elaborate.

**Comment by claussni** [comment]
Sure. Here is what I noticed:

* One assert statement per test
 Tests should in principle test one thing only. There might be more assert statements, if they all together check one "result" (like in the constructor test).
* Licence and copyright header per file
 ...but thats just a recommendation. 
* When overriding equals(), one should always override hashCode() as well
* You use String index methods a lot for syntax checking of DOI literals. I suggest replacing it with contains() method.
* API design wise, it might be a good idea to get rid of the static factory method class DOIUtil. It implements a lot of DOI specifics, which have a proper place in the DOI class already. 

Pull request code reviews are a very good way to collect reviews. You might want to request a review when you see a PR fit.

**Comment by jhpoelen** [comment]
@claussni Thanks for your comments. I took some time today to look at them and made some changes in https://github.com/globalbioticinteractions/doi4j/commit/be5bd98316b3d23c3f911b351d9964c13dafc13c .

More specifically - 

> One assert statement per test

Yep, got a bit lazy here. I made an effort to separate out the different test cases.

> Licence and copyright header per file

I prefer to stick with a license file at the base of the repo. I feel having license header per file clutters the source code and adds maintenance (updating copyright year etc). However, I might be convinced to use some copyright header generated using some maven plugin to avoid maintenance overhead.

> When overriding equals(), one should always override hashCode() as well

Thanks! I've added hashCode and equalsTo and associated test cases.

> You use String index methods a lot for syntax checking of DOI literals. I suggest replacing it with contains() method.

Wasn't quite sure about this one. String.indexOf is used to find the position of a character to validate and parse. Perhaps I missed something.

> API design wise, it might be a good idea to get rid of the static factory method class DOIUtil. It implements a lot of DOI specifics, which have a proper place in the DOI class already.

I moved the DOIUtil methods into DOI class as you suggested.

Thanks again for your comments. If you have some more suggestions, please propose changes via pull requests on https://github.com/globalbioticinteractions/doi4j or open an issue https://github.com/globalbioticinteractions/doi4j/issues/new .

**Pull request merged**
